source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '10.0'
target 'KIF-Quick_Example' do

  target 'KIF-Quick_Tests' do
    inherit! :search_paths

    pod 'KIF-Quick', :path => '../'
  end
end
